### ISSUE TITLE
Update to use Build Service v2 API endpoint

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/asana-bot#76]
At the lines below please update to use the v2 API endpoint `build.origami.ft.com/v2/bundles`

https://github.com/Financial-Times/asana-bot/blob/fceda75388e39a0a4169a63a8b56a03bb063b419/src/main/resources/templates/login/logout.html#L7 and L8

https://github.com/Financial-Times/asana-bot/blob/fceda75388e39a0a4169a63a8b56a03bb063b419/src/main/resources/templates/index.html#L6 and L7

https://github.com/Financial-Times/asana-bot/blob/e562623bd10459a9371cd57ffd0d2dbdac89e33e/src/main/resources/templates/reports/home.html#L8 and L9

https://github.com/Financial-Times/asana-bot/blob/92007bfd2e723e9506637a5b67529c6b4a935110/src/main/resources/templates/common.html#L8 and L9

**Comment by Lucas-Gluchowski** [comment]
Check https://github.com/Financial-Times/asana-bot/pull/77

**Comment by onishiweb** [comment]
Looks good, thanks @Lucas-Gluchowski
